FROM ubuntu:16.04

ARG MOSQUITTOVERSION
ENV MOSQUITTOVERSION 1.4.14

# File Author / Maintainer
MAINTAINER Mikael Trieb <mikael@smoofit.com>

ENV DEBIAN_FRONTEND noninteractive

# Update the repository sources list
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y wget

# Install dependencies
RUN apt-get install libwrap0-dev -y
RUN apt-get install python-distutils-extra -y
RUN apt-get install libc-ares-dev -y
RUN apt-get install uuid-dev -y
RUN apt-get install libssl-dev -y
RUN apt-get install libwebsockets-dev -y
RUN apt-get install build-essential -y
RUN apt-get install libcurl4-openssl-dev -y

# Download mosquitto source code
RUN wget http://mosquitto.org/files/source/mosquitto-1.4.14.tar.gz
RUN tar -zxvf mosquitto-1.4.14.tar.gz

WORKDIR mosquitto-1.4.14
# Edit config.mk WITH_WEBSOCKETS:=yes
RUN sed -i "s|WITH_WEBSOCKETS:=no|WITH_WEBSOCKETS:=yes|g" config.mk
RUN make
RUN make install
WORKDIR /

# Create folder to hold all configuration
RUN mkdir /opt/mosquitto

RUN adduser --system --disabled-password --disabled-login mosquitto
USER mosquitto

# Copy config files to image
# COPY config/conf.d/ /opt/mosquitto/conf.d/

# The folder with the cetificates are mounted from host at 'run'

# Expose ports to be used
EXPOSE 1883 8883 9001 9883

# Define
CMD /usr/local/sbin/mosquitto -c /opt/mosquitto/config/conf.d/mosquitto.conf
