version: '3'

services:
  mosquitto-service:
    build: .
    volumes:
      - /opt/mosquitto:/opt/mosquitto
      - /opt/mosquitto/logs:/var/log/mosquitto
      - /opt/mosquitto/certs/trusted:/etc/mosquitto/certs
    ports:
      - 8883:8883
      - 9883:9883
