version: '3'

services:
  mosquitto-service:
    build:
        context: .
        dockerfile: Dockerfile_source
    volumes:
      - /opt/mosquitto:/opt/mosquitto/:ro
      - /opt/mosquitto/logs/:/var/log/mosquitto
      - /opt/mosquitto/certs:/opt/mosquitto/certs:ro
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
      - 9883:9883
